# 2D Arrays Lecture

2D arrays are everywhere in astronomy as they are the main way that image data gets stored. And 2D arrays will  pop up if you are doing work that involves using linear algebra. 

To start working with 2D arrays let import Numpy into our program

In [105]:
import numpy as np

### Basics of a 2D array

2D arrays have the same structure and form as a matrix. If you have yet to see a matrix think of 2D arrays as a table. Where values are stored in rows and columns. Much like the diagram below.
 
     |  2  3  4  5|
     | 11 12 13 14|
     | 21 14 22 43|
     
Python allows you to work with 2D arrays and even allows you to perform algebraic expression on them.    

### Syntax for making a 2D array

In [8]:
twoDarray = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
twoDarray

array([[1, 2, 3],
       [4, 5, 6]])

Say that we want to get the number 5 from this 2D array the way to do this is by indicating row and column position. Looking at the output above we can see that 5 is on row 2 and column 2. In python this relates to row index 1 and column index 1

In [21]:
twoDarray[1,1]

5

Try to grab the number 2, 6, and 4 from this matrix.

In [ ]:
#write code for getting 2

In [ ]:
#write code for getting 6

In [22]:
#write code for getting 4

The general syntax for a 2D array is that you write out np.array to tell python you want this as an array. Then put lists within a list. In our list we have that [1,2,3] became the first row and that [4,5,6] became the second row. This means that if you added another list it would have gone to the third row. 

### Note:
The number of things in each row has to be the same

---

The general syntax for making an array

    np.array([ [row1], [row2], [row3], ...])
    

If you try to add a different number of elements for each row python will not read it as a 2D array. Run the code below and see what you get. 

In [23]:
test = np.array([[1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5, 6]])

In [24]:
test

array([list([1, 2, 3]), list([1, 2, 3, 4]), list([1, 2, 3, 4, 5, 6])],
      dtype=object)

Does this look like the twoDarray output above?

#### So what happened here? 

Essentially python tried its best to make a 2D array but because each list had a different number of values it interpreted that as you making lists within a list. 

You cannot index this as you would a 2D array. If you were to try then you would get an error.

In [134]:
test[1,2]

IndexError: too many indices for array

## Test

In [10]:
mystery = [[1, 2, 3], [4, 5, 6]]

In [11]:
mystery

[[1, 2, 3], [4, 5, 6]]

Take a look at mystery and twoDarray. Would you say that mystery is a 2D array?

## Another way to make 2D arrays

If we make a 2D array using the syntax above it would take a very long time to write out something that needs to be stored in a 2D array with 100 rows and 100 columns. Luckily for us python has the capability of generating these 2D arrays with little effort.

The syntax for this is:

In [111]:
quick_2D = np.zeros((4,4))

In [112]:
quick_2D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

This makes an empty array with dimensions (n,m) that you pass in the np.zeros.

These are particularly good if you want a quick way of making an empty matrix where you can then append values to it.

In [109]:
another_quick2D = np.ones((7, 5))

In [110]:
another_quick2D

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

You can also create 2D arrays by reshaping 1D arrays.

In [12]:
x = np.zeros(16)

twoD_x = x.reshape((4,4))

## Note:

The reshaping of the 1D array has to be done with an (x, y) such that the product of x and y equals the length of the 1D array. In other words if you have a 1D array that has a length of 16 you can reshape it to be (4,4) or (2,8) or (8, 2)

In [117]:
x1 = np.arange(1,16)

reshape1 = x1.reshape((5,3))
reshape2 = x1.reshape((3,5))

In [118]:
reshape1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [119]:
reshape2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## Splicing and Striding with 2D arrays

We talked a little bit about how to extract one value in an array but what if you wanted to extract a whole row, a whole column. Maybe you want to only look at a small portion of the 2D array. I will show you how to do this and more in the following section.

### Review of 1D splicing and striding

In [25]:
oneDarray = np.arange(1, 21)

In [26]:
first_half = oneDarray[:len(oneDarray)//2]

In [27]:
first_half

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
other_half = oneDarray[len(oneDarray)//2:]

In [29]:
other_half

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
between = oneDarray[5:15]

In [39]:
between

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Recall what the data[:ind] notation means. It means give me the values of data from index 0 to index ind-1 because this notation does not include the index ind.

In data[ind:] this means give me the values of data from index ind to the end of data.

data[index1:index2] tells you give me the values of data from index1 to index2-1

In [30]:
every_two = oneDarray[::2]

In [31]:
every_two

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
every_4 = oneDarray[::4]

In [33]:
every_4

array([ 1,  5,  9, 13, 17])

In this notation data[::2] the first colon tells you to go through the whole array and the second colon tells you how many data values to skip in this case 2.

In [34]:
every_two_until_10 = oneDarray[:len(oneDarray)//2:2]

In [35]:
every_two_until_10

array([1, 3, 5, 7, 9])

In [36]:
every_two_after_10 = oneDarray[len(oneDarray)//2::2]

In [37]:
every_two_after_10

array([11, 13, 15, 17, 19])

In [122]:
between_every_other = oneDarray[5:15:2]

In [123]:
between_every_other

array([ 6,  8, 10, 12, 14])

Recall that if you put indices in the first colon you shrink the array down to focus within that interval then perfroms the striding.

### Applying Splicing and Striding to 2D arrays

The rules of splicing and striding still apply even in 2D arrays, its just that now you have two coordinates to take into account.

In [45]:
#making a 2D array
matrix = np.arange(1, 21).reshape(4,5)

In [46]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

To take any row we have to specify which row we want and make sure that we get all the column elements.

In [ ]:
#getting first row
first_row = matrix[0, :]

Let's take this apart the 0 indicates the row we want to take and the : in the column sections tells python to give me all the values in the columns. 

Which is very similar to 1D splicing and striding.

In [47]:
#try taking the 4th row
fourth_row = 

To take a column we do something similar but now switch the order. To get a column we want every row element but only a specific column

In [48]:
second_column = matrix[:, 1]

In [49]:
second_column

array([ 2,  7, 12, 17])

Now lets introduce striding

The two examples below show how this applies to getting every-other row and column

In [50]:
every_other_row = matrix[::2,:]

In [51]:
every_other_row

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [52]:
every_other_column = matrix[:,::2]

In [53]:
every_other_column

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

Just as striding with 1D arrays allows you to quickly change values you can also do the same in 2D arrays

In [62]:
#changing first columns to 5
matrix[:,0] = 5

In [63]:
matrix

array([[ 5,  2,  3,  4,  5],
       [ 5,  7,  8,  9, 10],
       [ 5, 12, 13, 14, 15],
       [ 5, 17, 18, 19, 20]])

In [64]:
#changing first row to 3
matrix[0,:] = 3

In [65]:
matrix

array([[ 3,  3,  3,  3,  3],
       [ 5,  7,  8,  9, 10],
       [ 5, 12, 13, 14, 15],
       [ 5, 17, 18, 19, 20]])

In [67]:
#making upper right corner 1
matrix[:2, 3:] = 1

In [68]:
matrix

array([[ 3,  3,  3,  1,  1],
       [ 5,  7,  8,  1,  1],
       [ 5, 12, 13, 14, 15],
       [ 5, 17, 18, 19, 20]])

## Mathematical Operations on 2D arrays

In [76]:
ones_ = np.ones((5,5))

In [77]:
ones_

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
ones_plus_5 =  ones_ + 5

In [75]:
ones_plus_5

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [72]:
ones_times_3 = ones_ * 3

In [78]:
ones_times_3

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [73]:
ones_minus_4 = ones_ - 4

In [79]:
ones_minus_4

array([[-3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3.]])

In [74]:
ones_divided_3 = ones_/3

In [80]:
ones_divided_3

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]])

The way that any mathematical operation is done on a 2D array is that every element undergoes the operation as can be seen from the examples above. However, mathematical operations can also be done between 1D arrays and other 2D arrays.

## 2D and 1D math

In [81]:
mat = 5* np.ones((6,6))

In [86]:
mat

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

In [84]:
one = np.arange(6)

In [87]:
one

array([0, 1, 2, 3, 4, 5])

In [85]:
mat-one

array([[5., 4., 3., 2., 1., 0.],
       [5., 4., 3., 2., 1., 0.],
       [5., 4., 3., 2., 1., 0.],
       [5., 4., 3., 2., 1., 0.],
       [5., 4., 3., 2., 1., 0.],
       [5., 4., 3., 2., 1., 0.]])

When you try to do math operations between 1D arrays and 2D arrays what will happen is that every row will have the operation.

In the example above the 1D array labeled one was subtracted from every row of the matrix mat. And it did it with like indexes meaning that the first column was all subtracted by 0 second column was subtracted by 1, third column by 2 and so on.

In [88]:
short = np.arange(4)

In [89]:
mat-short

ValueError: operands could not be broadcast together with shapes (6,6) (4,) 

### Note:
In order for mathematical operations to work between 2D arrays and 1D arrays the number of coulmns in the 2D array must equal the number of elements in the 1D array

## 2D and 2D math

In [96]:
base = 2*np.ones((4,4))

In [97]:
base

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [98]:
math = np.arange(16).reshape(4,4)

In [99]:
math

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [100]:
base+math

array([[ 2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9.],
       [10., 11., 12., 13.],
       [14., 15., 16., 17.]])

In [101]:
base*math

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.],
       [24., 26., 28., 30.]])

In [103]:
math/base

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5],
       [6. , 6.5, 7. , 7.5]])

In [104]:
base-math

array([[  2.,   1.,   0.,  -1.],
       [ -2.,  -3.,  -4.,  -5.],
       [ -6.,  -7.,  -8.,  -9.],
       [-10., -11., -12., -13.]])

The way that 2D math works is element wise meaning that the value at the same index in both 2D arrays are undergoing the operation. 

## Linear Algebra

Numpy also has packages to deal with linear algebra. 

In [124]:
from numpy import linalg

In [127]:
matrix = np.arange(1, 17).reshape(4,4)

Getting determinant

In [128]:
linalg.det(matrix)

-1.820448242817726e-31

Finding Eigenvalues to save the Universe

In [129]:
linalg.eigvals(matrix)

array([ 3.62093727e+01, -2.20937271e+00, -2.91421324e-15, -5.70557534e-16])

Matrix Multiplication

In [131]:
matrix2 = np.arange(20, 36).reshape(4,4)

In [132]:
np.dot(matrix, matrix2)

array([[ 280,  290,  300,  310],
       [ 696,  722,  748,  774],
       [1112, 1154, 1196, 1238],
       [1528, 1586, 1644, 1702]])

In [133]:
oneDarr = np.arange(5, 9)

np.dot(matrix2, oneDarr)

array([564, 668, 772, 876])